#!/usr/bin/env bash
#script replicates 4-to_infinity_and_beyond
#prints I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

while true; do
echo "To infinity and beyond"
sleep 2
done
